### ISSUE TITLE
Where I download .ipk files?

### ISSUE THREAD

**Issue by tuxevil** [4IceG/luci-app-sms-tool#1]
Hi 4lceG, Im wanting to try your tool but I cant find the files .ipk you mention in the installation guide

**Comment by 4IceG** [comment]
Hi tuxevil, I didn't share the .ipk files because the sms-tool package itself compiles for individual platforms. I can add it for the routers I use, but I don't know if there are the same files on every device. I recommend to download sources and compile your own image with my package added. 
[sms-tool_2020-08-10-1cd967c4-1_arm_cortex-a9_vfpv3-d16.zip](https://github.com/4IceG/luci-app-sms-tool/files/5321178/sms-tool_2020-08-10-1cd967c4-1_arm_cortex-a9_vfpv3-d16.zip)

**Comment by tuxevil** [comment]
oh ok, great, thanks! i will try it
