### ISSUE TITLE
qmi-utils

### ISSUE THREAD

**Issue by AZBoxEmperador** [4IceG/luci-app-sms-tool#6]
Please make you build to use qmi-utils instead, so it can detect almost every MODEM connected to the router

![image](https://user-images.githubusercontent.com/4449023/131530591-6badd3e2-28f4-460c-bd40-7366be755be6.png)

**Comment by 4IceG** [comment]
If the application has not detected the port for communication with the modem, you can always add it or enter it manually. If that helps, I can add a selection of "/ dev / cdc-wdm" devices in the next edition.

**Comment by AZBoxEmperador** [comment]
Yes I did it, and it didn't work, please provide the steps in order to compile myself.

Thanks

**Comment by 4IceG** [comment]
If manually adding a port didn't help, then there is no point in adding something that won't work anyway. Which means that for proper operation, communication with the modem is required an appropriate ttyUSB port.

Compilation of the sms-tool / packages does not differ from the compilation of other packages for OpenWrt. It is best to download the sources and add applications to the image being built, because you will have to compile the environment for the architecture anyway.
